### ISSUE TITLE
NEED HELP CLEARING THE PAINTWINDOW!!!!

### ISSUE THREAD

**Issue by mestrinio** [mestrinio/Avaliacao2-PSR#3]
https://github.com/mestrinio/Avaliacao2-PSR/blob/7158ed0bca63510b5955b4b51ef3ca616cf2c68e/ar_paint3.py#L146-L152

can't make keyboardpress function clear work, the program freezes everytime the right color is detected when i implement these lines on the code, but it comes back as soon as i remove my phone from the front of the camera

**Comment by tomastaxa31** [comment]
Era só tirar o 
else:
       continue
